// This file will be auto-generated by: npx supabase gen types typescript
// For now, we define a minimal placeholder that matches the expected schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          display_name: string;
          avatar_url: string | null;
          phone: string | null;
          birthday: string | null;
          anniversary: string | null;
          special_occasions: Json | null;
          bio: string | null;
          interests: string | null;
          dislikes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name: string;
          avatar_url?: string | null;
          phone?: string | null;
          birthday?: string | null;
          anniversary?: string | null;
          special_occasions?: Json | null;
          bio?: string | null;
          interests?: string | null;
          dislikes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string;
          avatar_url?: string | null;
          phone?: string | null;
          birthday?: string | null;
          anniversary?: string | null;
          special_occasions?: Json | null;
          bio?: string | null;
          interests?: string | null;
          dislikes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      registries: {
        Row: {
          id: string;
          owner_id: string;
          title: string;
          description: string | null;
          occasion: string | null;
          occasion_date: string | null;
          is_public: boolean;
          cover_image_url: string | null;
          slug: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          title: string;
          description?: string | null;
          occasion?: string | null;
          occasion_date?: string | null;
          is_public?: boolean;
          cover_image_url?: string | null;
          slug: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          occasion?: string | null;
          occasion_date?: string | null;
          is_public?: boolean;
          cover_image_url?: string | null;
          slug?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      registry_items: {
        Row: {
          id: string;
          registry_id: string;
          name: string;
          description: string | null;
          price: number | null;
          currency: string;
          url: string | null;
          image_url: string | null;
          priority: number;
          notes: string | null;
          quantity_desired: number;
          quantity_purchased: number;
          is_archived: boolean;
          sort_order: number;
          store_name: string | null;
          store_address: string | null;
          store_lat: number | null;
          store_lng: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          registry_id: string;
          name: string;
          description?: string | null;
          price?: number | null;
          currency?: string;
          url?: string | null;
          image_url?: string | null;
          priority?: number;
          notes?: string | null;
          quantity_desired?: number;
          quantity_purchased?: number;
          is_archived?: boolean;
          sort_order?: number;
          store_name?: string | null;
          store_address?: string | null;
          store_lat?: number | null;
          store_lng?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          price?: number | null;
          currency?: string;
          url?: string | null;
          image_url?: string | null;
          priority?: number;
          notes?: string | null;
          quantity_desired?: number;
          quantity_purchased?: number;
          is_archived?: boolean;
          sort_order?: number;
          store_name?: string | null;
          store_address?: string | null;
          store_lat?: number | null;
          store_lng?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      purchases: {
        Row: {
          id: string;
          item_id: string;
          purchaser_id: string;
          quantity: number;
          is_purchased: boolean;
          is_anonymous: boolean;
          notes: string | null;
          purchased_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          purchaser_id: string;
          quantity?: number;
          is_purchased?: boolean;
          is_anonymous?: boolean;
          notes?: string | null;
          purchased_at?: string;
          created_at?: string;
        };
        Update: {
          quantity?: number;
          is_purchased?: boolean;
          notes?: string | null;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          subscriber_id: string;
          registry_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          subscriber_id: string;
          registry_id: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          role?: string;
        };
        Relationships: [];
      };
      user_contacts: {
        Row: {
          id: string;
          user_id: string;
          contact_email: string | null;
          contact_phone: string | null;
          matched_user_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          matched_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          contact_email?: string | null;
          contact_phone?: string | null;
          matched_user_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      invitations: {
        Row: {
          id: string;
          registry_id: string;
          invited_by: string;
          invite_token: string;
          invited_email: string | null;
          role: string;
          accepted_at: string | null;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          registry_id: string;
          invited_by: string;
          invite_token: string;
          invited_email?: string | null;
          role?: string;
          accepted_at?: string | null;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          accepted_at?: string | null;
          role?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          data: Json | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          data?: Json | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          is_read?: boolean;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      accept_invitation: {
        Args: { p_token: string };
        Returns: Json;
      };
      follow_registry: {
        Args: { p_registry_id: string };
        Returns: Json;
      };
      get_thank_you_purchases: {
        Args: { p_registry_id: string };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
